# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d9d9d35d9020c2e2c6e96e34b98c1af3001e57b578ef1c5d3605875e26498c60e56536c10ddeb84dbf379a8707863635a58abe2a192a3368c88292e841edd7

test:
  secret_key_base: 4123c0b6383de2774c1c57b1ff0406d3496527457ef36122e59cc2240ab0ec9e128378cd7d3736a8b2825ceb10f946a3cf266c34079401f423c87abc9a8a942c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
